package com.i5le.redplus.entity;

// Generated 2014-10-15 17:16:53 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.i5le.framwork.core.entity.IdEntity;

/**
 * UserGift generated by hbm2java
 */
@Entity
@Table(name = "redplus_money")
public class RedplusMoney extends IdEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2863881066616818291L;
	/**
	 * 
	 */

	
	private Long money;

	@Column(name="money")
	public Long getMoney() {
		return money;
	}

	public void setMoney(Long money) {
		this.money = money;
	}
	
}
