package com.i5le.redplus.entity;
// Generated 2014-10-15 17:16:53 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.i5le.framwork.core.entity.IdEntity;

/**
 * TransRebate generated by hbm2java
 */
@Entity
@Table(name="trans_rebate"
)
public class TransRebate  extends IdEntity implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -2130658007143183406L;

     private int transId;
     private int statu;
     private int money;
     private Date createtime;
     private String remark;
     private String resv1;
     private String resv2;
     private String resv3;

    public TransRebate() {
    }

   
   
 
    
    @Column(name="trans_id", nullable=false)
    public int getTransId() {
        return this.transId;
    }
    
    public void setTransId(int transId) {
        this.transId = transId;
    }
    
    @Column(name="statu", nullable=false)
    public int getStatu() {
        return this.statu;
    }
    
    public void setStatu(int statu) {
        this.statu = statu;
    }
    
    @Column(name="money", nullable=false)
    public int getMoney() {
        return this.money;
    }
    
    public void setMoney(int money) {
        this.money = money;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="createtime", nullable=false, length=10)
    public Date getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
    
    @Column(name="remark", nullable=false, length=220)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="resv1", nullable=false, length=20)
    public String getResv1() {
        return this.resv1;
    }
    
    public void setResv1(String resv1) {
        this.resv1 = resv1;
    }
    
    @Column(name="resv2", nullable=false, length=100)
    public String getResv2() {
        return this.resv2;
    }
    
    public void setResv2(String resv2) {
        this.resv2 = resv2;
    }
    
    @Column(name="resv3", nullable=false, length=200)
    public String getResv3() {
        return this.resv3;
    }
    
    public void setResv3(String resv3) {
        this.resv3 = resv3;
    }




}


