package com.i5le.redplus.entity;

// Generated 2014-10-15 17:16:53 by Hibernate Tools 3.2.2.GA

import java.util.Comparator;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.springframework.transaction.annotation.Transactional;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.i5le.framwork.core.entity.IdEntity;

/**
 * UserInfo generated by hbm2java
 */
@Entity
@Table(name = "user_info")
public class UserInfo extends IdEntity implements java.io.Serializable{

	private static final long serialVersionUID = -501799832590244011L;

	private String nickname;
	private Integer age;
	private Integer height;
	private Integer weight;
	private String hobby;
	private String iconimg;
	private String area;
	private Integer gender;
	private String telpone;
	private String loginname;
	private String passwd;

	private Integer online;
	private String remark;
	private String coll;
	private String refreeUser;
	private String resv1;
	private String resv2;
	private String resv3;
	private byte[] icon;
	private Integer type_map;
	@Column(name = "sort_value")
	private Integer sort_value;
	
	public Integer getSort_value() {
		return sort_value;
	}

	public void setSort_value(Integer sort_value) {
		this.sort_value = sort_value;
	}

	@Column(name = "type_map")
	public Integer getType_map() {
		return type_map;
	}

	public void setType_map(Integer type_map) {
		this.type_map = type_map;
	}

	private Long money;
	
	private long gold;
	
	@OneToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="user_id")
	private UserMoney userMoney;
	
	private String showNow;

	@Column(name = "shownow")
	public String getShowNow() {
		return showNow;
	}

	public void setShowNow(String showNow) {
		this.showNow = showNow;
	}

	@Transient
	public Long getMoney() {
		if(userMoney==null||userMoney.getMoney()==null){
			return 0L;
		}else {
			return userMoney.getMoney();
		}
	}

	@Transient
	public long getGold() {
		return gold;
	}

	public void setGold(long gold) {
		this.gold = gold;
	}

	public void setMoney(Long money) {
		this.money = money;
	}

	public UserInfo() {
	}

	@Column(name = "nickname", length = 22)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "height")
	public Integer getHeight() {
		return this.height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	@Column(name = "weight")
	public Integer getWeight() {
		return this.weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	@Column(name = "hobby", length = 200)
	public String getHobby() {
		return this.hobby;
	}

	public void setHobby(String hobby) {
		this.hobby = hobby;
	}

	@Column(name = "iconimg", length = 200)
	public String getIconimg() {
		return this.iconimg;
	}

	public void setIconimg(String iconimg) {
		this.iconimg = iconimg;
	}

	@Column(name = "area", length = 200)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "gender")
	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}

	@Column(name = "telpone")
	public String getTelpone() {
		return this.telpone;
	}

	public void setTelpone(String telpone) {
		this.telpone = telpone;
	}

	@Column(name = "loginname", length = 100)
	public String getLoginname() {
		return this.loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	@Column(name = "passwd", length = 20)
	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	@Column(name = "online")
	public Integer getOnline() {
		return this.online;
	}

	public void setOnline(Integer online) {
		this.online = online;
	}

	@Column(name = "remark", length = 220)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "coll",

	length = 220)
	public String getColl() {
		return this.coll;
	}

	public void setColl(String coll) {
		this.coll = coll;
	}

	@Column(name = "resv1", length = 20)
	public String getResv1() {
		return this.resv1;
	}

	public void setResv1(String resv1) {
		this.resv1 = resv1;
	}

	@Column(name = "resv2", length = 100)
	public String getResv2() {
		return this.resv2;
	}

	public void setResv2(String resv2) {
		this.resv2 = resv2;
	}

	@Column(name = "resv3", length = 200)
	public String getResv3() {
		return this.resv3;
	}

	public void setResv3(String resv3) {
		this.resv3 = resv3;
	}

	@Column(name = "icon")
	public byte[] getIcon() {
		return this.icon;
	}

	public void setIcon(byte[] icon) {
		this.icon = icon;
	}

	@Column(name = "refree")
	public String getRefreeUser() {
		return refreeUser;
	}

	public void setRefreeUser(String refreeUser) {
		this.refreeUser = refreeUser;
	}
}
