package com.i5le.redplus.entity;

// Generated 2014-10-15 17:16:53 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.i5le.framwork.core.entity.IdEntity;

/**
 * UserGift generated by hbm2java
 */
@Entity
@Table(name = "user_gift")
public class UserGift extends IdEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6489697067570849763L;
	private int userId;
	private GiftInfo gift;
	private int order;
	private int price;
	private String resv1;

	public UserGift() {
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "orders", nullable = false)
	public int getOrder() {
		return this.order;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "gift_id")
	public GiftInfo getGift() {
		return gift;
	}

	public void setGift(GiftInfo gift) {
		this.gift = gift;
	}

	public void setOrder(int order) {
		this.order = order;
	}

	@Column(name = "price", nullable = false)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	@Column(name = "resv1")
	public String getResv1() {
		return this.resv1;
	}

	public void setResv1(String resv1) {
		this.resv1 = resv1;
	}

}
