package com.i5le.redplus.entity;

// Generated 2014-10-15 17:16:53 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.google.gson.annotations.Expose;
import com.i5le.framwork.core.entity.IdEntity;

/**
 * UserTransInfo generated by hbm2java
 */
@Entity
@Table(name = "user_trans_info")
public class UserTransInfo extends IdEntity implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 2249156943658245598L;

	
	private Long transid;
	
	private UserGift userGift;
	//private Integer userGiftId;
	private Integer count;
	private Integer type;
	private String resv1;

	

	
	@Column(name = "trans_id")
	public Long getTransid() {
		return transid;
	}




	public void setTransid(Long transid) {
		this.transid = transid;
	}




	
	
	

	
	@OneToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="user_gift_id")
	public UserGift getUserGift() {
		return userGift;
	}




	public void setUserGift(UserGift userGift) {
		this.userGift = userGift;
	}




//	@Column(name = "user_gift_id")
//	public Integer getUserGiftId() {
//		return this.userGiftId;
//	}
//
//	public void setUserGiftId(Integer userGiftId) {
//		this.userGiftId = userGiftId;
//	}

	@Column(name = "count")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "resv1", length = 100)
	public String getResv1() {
		return this.resv1;
	}

	public void setResv1(String resv1) {
		this.resv1 = resv1;
	}

}
