package com.i5le.redplus.entity;

// Generated 2014-10-15 17:16:53 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.i5le.framwork.core.entity.IdEntity;

/**
 * UserTrans generated by hbm2java
 */
@Entity
@Table(name = "user_trans")
public class UserTrans extends IdEntity implements java.io.Serializable {

	public transient static final int TRANS_BEGIN = 0;
	public transient static final int TRANS_OK = 1;
	public transient static final int TRANS_BAD = -1;

	public transient static final int TRANS_OVER = 2;
	/**
	 * 
	 */
	private static final long serialVersionUID = 8066923121486621841L;

	private UserInfo fromUser;
	private UserInfo toUser;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "from_user_id")
	public UserInfo getFromUser() {
		return fromUser;
	}

	public void setFromUser(UserInfo fromUser) {
		this.fromUser = fromUser;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "to_user_id")
	public UserInfo getToUser() {
		return toUser;
	}

	public void setToUser(UserInfo toUser) {
		this.toUser = toUser;
	}

	private Date createtime;
	private Integer statu;
	private String resv1;
	private String resv2;
	private String resv3;
	private Long countMoney;
	private List<UserTransInfo> transInfo;

	@Column(name = "countMoney")
	public Long getCountMoney() {
		return countMoney;
	}

	public void setCountMoney(Long countMoney) {
		this.countMoney = countMoney;
	}

	@OneToMany(fetch = FetchType.EAGER, cascade = { CascadeType.PERSIST })
	@JoinColumn(name = "trans_id")
	public List<UserTransInfo> getTransInfo() {
		return transInfo;
	}

	public void setTransInfo(List<UserTransInfo> transInfo) {
		this.transInfo = transInfo;
	}

	public UserTrans() {
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime")
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Column(name = "statu")
	public Integer getStatu() {
		return this.statu;
	}

	public void setStatu(Integer statu) {
		this.statu = statu;
	}

	@Column(name = "resv1", length = 20)
	public String getResv1() {
		return this.resv1;
	}

	public void setResv1(String resv1) {
		this.resv1 = resv1;
	}

	@Column(name = "resv2", length = 100)
	public String getResv2() {
		return this.resv2;
	}

	public void setResv2(String resv2) {
		this.resv2 = resv2;
	}

	@Column(name = "resv3", length = 200)
	public String getResv3() {
		return this.resv3;
	}

	public void setResv3(String resv3) {
		this.resv3 = resv3;
	}

}
